version: "2"
services:
  web:
    image: web:v1
    depends_on:
    - catalogue
    ports:
    - "80:80"
    container_name: web
  catalogue: 
    image: catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
    ports:
    - "8080"
    environment:
      MONGO_URL: mongodb://mongodb:27017/catalogue
  mongodb:
    image: mongodb:v1
    container_name: mongodb 
    ports:
    - "27017:27017"
  user:
    image: user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
    ports:
    - "8080"
  redis:
    image: redis
  cart:
    image: cart:v1
    container_name: cart
    ports:
    - "8080"
    depends_on:
    - catalogue
    - redis
    - shipping
  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    ports:
    - "8080"
  mysql:
    image: mysql:v1
    container_name: mysql
    


